Technical task sprint 6
Alexey500312/java-kanban pull request #1
Opened 2024-10-13 13:13 UTC by Alexey500312

2024-10-14 16:55 UTC, YazykovMikhail requested changes

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +    public void remove(int id) {
Можно вот так оптимизировать 
```

	public void remove(int id) {
		final Node node = history.remove(id);
		if (node == null) {
			return;
		}
		removeNode(node);
	}
```

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +    public void remove(int id) {
Метод remove - удаляет
removeNode - настраивает ссыки после удаления

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +        removeNode(node);
Соответсвенно тут можно будет вызывать:

		final int id = task.getId();
		remove(id);

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +    private void addNode(Task task) {
private void linkLast(Task task) { - стоит назвать как скзаано в заднии

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +        history.put(task.getId(), newNode);
а сам linkLast не добавляет, а настраивет ссылки - это разные опеарции, у тебя есть метод add в котором и будет добавление
отсюда стоит убрать добавление

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +        addNode(task);
linkLast(task);
		history.put(id, last);

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +        if (node == null) {
после рефакторинга эта проверка будет излишне

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +        history.remove(task.getId());
после рефакторинга тут удаление будет излише

2024-10-14 16:55 UTC, YazykovMikhail commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +    Node first;
private

2024-10-14 17:18 UTC, Alexey500312 commented on src/ru/yandex/javacource/e/schedule/service/InMemoryHistoryManager.java
> +    public void remove(int id) {
Поправил

2024-10-15 14:30 UTC, YazykovMikhail approved these changes

2024-10-15 19:40 UTC, merged